"""Initial schema

Revision ID: 3c8d6a98644d
Revises: 
Create Date: 2025-12-05 11:13:45.603707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8d6a98644d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('TASK', 'DECISION', 'OBLIGATION', 'QUESTION', 'ACTION_ITEM', 'NOTE', 'ANNOUNCEMENT', name='itemtype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'DEFERRED', 'CANCELLED', 'STALE', 'DONE', name='itemstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.String(length=50), nullable=True),
    sa.Column('source_channel_id', sa.String(length=50), nullable=True),
    sa.Column('source_channel_name', sa.String(length=100), nullable=True),
    sa.Column('source_thread_ts', sa.String(length=50), nullable=True),
    sa.Column('source_message_ts', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_user_name', sa.String(length=100), nullable=True),
    sa.Column('requestor_user_id', sa.String(length=50), nullable=True),
    sa.Column('requestor_user_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=50), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('labels', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_thread_ts', sa.String(length=50), nullable=True),
    sa.Column('source_channel_id', sa.String(length=50), nullable=True),
    sa.Column('source_message_ts', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_titles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('thread_ts', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('inferred_by', sa.String(length=50), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_ts')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.Column('focus_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('focus_mode_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_name', sa.String(length=200), nullable=True),
    sa.Column('watched_channels', sa.Text(), nullable=True),
    sa.Column('important_channels', sa.Text(), nullable=True),
    sa.Column('ignored_channels', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('agenda_item_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('agenda_item_id', sa.String(length=36), nullable=True),
    sa.Column('thread_ts', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('decision_message_ts', sa.String(length=50), nullable=True),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('involved_user_ids', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_table('agenda_item_history')
    op.drop_table('workspace_configs')
    op.drop_table('views')
    op.drop_table('user_profiles')
    op.drop_table('thread_titles')
    op.drop_table('faq_answers')
    op.drop_table('agenda_items')
    # ### end Alembic commands ###
